version: '3'
services:
  nginx:
    build:
      context: ./requirements/nginx
    image: rtruvelo/nginx:v1
    container_name: nginx
    ports:
      - "443:443"
    volumes:
     - wordpress_data:/var/www/html
    networks:
      - my_network
    restart: on-failure
  
  wordpress:
    build:
      context: ./requirements/wordpress
    image: rtruvelo/wordpress:v1
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    networks:
      - my_network
    

  mariadb:
    build:
      context: ./requirements/mariadb
    image: rtruvelo/mariadb:v1
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./requirements/mariadb/conf/my.conf:/etc/mysql/my.cnf
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rtruvelo/data/db_data
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rtruvelo/data/wordpress_data